version: '3'

services:
  php:
    image: php:7.3-apache
    volumes:
      - ./pages/:/var/www/html/
    ports:
      - 8088:80
    environment:
      - SECRET=f143b7b9-f032-4847-a789-41f77c71ce9fb95fba76-5966-4bc7-9f28-000000000000
      - CORS_DOMAIN=http://localhost:9000
