ROUTE_HOST: ice-dragon.ose3.puzzle.ch
ROUTE_HOST_CONTENT_DEMO: ice-dragon-content-demo.ose3.puzzle.ch
JHIPSTER_MAIL_BASE_URL: 'https://ice-dragon.ose3.puzzle.ch'
JHIPSTER_MAIL_FROM: 'lightning@puzzle.ch'
JHIPSTER_CORS_ALLOWED_ORIGINS: ''
SPRING_LIQUIBASE_DROP_FIRST: true
SPRING_LIQUIBASE_CONTEXTS: dev
SPRING_MAIL_HOST: mail.puzzle.ch
SPRING_MAIL_PORT: 25
ROUTE_INSECURE_TRAFFIC: Allow
POSTGRESQL_PASSWORD: KGo1CpbU1Dj58FYW
APPLICATION_LND_HOST: not-commited-to-git-entered-manually-on-platform
APPLICATION_LND_PORT: 10009
APPLICATION_LND_INVOICE_MACAROON_HEX: not-commited-to-git-entered-manually-on-platform
APPLICATION_LND_READONLY_MACAROON_HEX: not-commited-to-git-entered-manually-on-platform
CONTENT_DEMO_SECRET: f143b7b9-f032-4847-a789-41f77c71ce9fb95fba76-5966-4bc7-9f28-37c67c5bded0
CONTENT_DEMO_CORS_DOMAIN: https://ice-dragon.ose3.puzzle.ch
